version: "3.8"

services:
    django:
        build: ./backend/data_gatherer
        container_name: data-gatherer-server
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env.docker
        volumes:
            - ./backend/data_gatherer/:/srv/app
            - prod_static:/srv/app/static
            - prod_media:/srv/app/media
        depends_on:
            - db
    react:
        build: ./frontend
        container_name: data-gatherer-client
        command: "npx serve build -p 3000 --single"
        env_file:
            - .env.docker
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./frontend/:/srv/app
            - prod_node_modules:/srv/app/node_modules
        depends_on:
            - django
    db:
        image: postgres:16.1-alpine
        container_name: prod-swang-db
        env_file:
            - .env.docker
        volumes:
            - prod_postgres_data:/var/lib/postgresql/data
    nginx:
        build: ./nginx
        container_name: prod-nginx
        ports:
            - 8080:80
        restart: always
        volumes:
            - prod_static:/srv/app/static
            - prod_media:/srv/app/media
        depends_on:
            - django
            - react
            - db

volumes:
    prod_node_modules:
    prod_postgres_data:
    prod_media:
    prod_static:
